apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ui
    name: ui
    type: web
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      name: ui
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
        name: ui
        type: web
      name: ui
    spec:
      containers:
      - image: sheriff/ui:1.0.{{build.number}}
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quayregistrykey
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
